# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tbaptiste/OOP_indie_studio_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tbaptiste/OOP_indie_studio_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbaptiste/OOP_indie_studio_2018/CMakeFiles /home/tbaptiste/OOP_indie_studio_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbaptiste/OOP_indie_studio_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/Core.o: src/Core.cpp.o

.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i

.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s

.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/MyEventReceiver.o: src/MyEventReceiver.cpp.o

.PHONY : src/MyEventReceiver.o

# target to build an object file
src/MyEventReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MyEventReceiver.cpp.o
.PHONY : src/MyEventReceiver.cpp.o

src/MyEventReceiver.i: src/MyEventReceiver.cpp.i

.PHONY : src/MyEventReceiver.i

# target to preprocess a source file
src/MyEventReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MyEventReceiver.cpp.i
.PHONY : src/MyEventReceiver.cpp.i

src/MyEventReceiver.s: src/MyEventReceiver.cpp.s

.PHONY : src/MyEventReceiver.s

# target to generate assembly for a file
src/MyEventReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MyEventReceiver.cpp.s
.PHONY : src/MyEventReceiver.cpp.s

src/Option.o: src/Option.cpp.o

.PHONY : src/Option.o

# target to build an object file
src/Option.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Option.cpp.o
.PHONY : src/Option.cpp.o

src/Option.i: src/Option.cpp.i

.PHONY : src/Option.i

# target to preprocess a source file
src/Option.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Option.cpp.i
.PHONY : src/Option.cpp.i

src/Option.s: src/Option.cpp.s

.PHONY : src/Option.s

# target to generate assembly for a file
src/Option.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Option.cpp.s
.PHONY : src/Option.cpp.s

src/Pause.o: src/Pause.cpp.o

.PHONY : src/Pause.o

# target to build an object file
src/Pause.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Pause.cpp.o
.PHONY : src/Pause.cpp.o

src/Pause.i: src/Pause.cpp.i

.PHONY : src/Pause.i

# target to preprocess a source file
src/Pause.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Pause.cpp.i
.PHONY : src/Pause.cpp.i

src/Pause.s: src/Pause.cpp.s

.PHONY : src/Pause.s

# target to generate assembly for a file
src/Pause.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Pause.cpp.s
.PHONY : src/Pause.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Select.o: src/Select.cpp.o

.PHONY : src/Select.o

# target to build an object file
src/Select.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Select.cpp.o
.PHONY : src/Select.cpp.o

src/Select.i: src/Select.cpp.i

.PHONY : src/Select.i

# target to preprocess a source file
src/Select.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Select.cpp.i
.PHONY : src/Select.cpp.i

src/Select.s: src/Select.cpp.s

.PHONY : src/Select.s

# target to generate assembly for a file
src/Select.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Select.cpp.s
.PHONY : src/Select.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/MyEventReceiver.o"
	@echo "... src/MyEventReceiver.i"
	@echo "... src/MyEventReceiver.s"
	@echo "... src/Option.o"
	@echo "... src/Option.i"
	@echo "... src/Option.s"
	@echo "... src/Pause.o"
	@echo "... src/Pause.i"
	@echo "... src/Pause.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Select.o"
	@echo "... src/Select.i"
	@echo "... src/Select.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

